function Plotransfertogether(Out,t)
f1=figure
sgtitle('Step Response')
subplot(2,2,1)
for i=1:length(Out)
[x,t]=step(Out{i}.dd,t)
plot(t,x,'DisplayName',Out{i}.name)
sgtitle('Step Response')
hold on
legend show
title('Ydd')
end
subplot(2,2,2)
for i=1:length(Out)
step(Out{i}.dq,t)
hold on
title('Ydq')
end
subplot(2,2,3)
step(Out1.qd,t)
title('Ydq')
subplot(2,2,4)
step(Out1.qq,t)
title('Yqq')
saveas(f1,['step' Out1.name '.emf'])
saveas(f1,['step' Out1.name '.jpeg'])
savefig(f1,['step' Out1.name])
%%
f2=figure
sgtitle(['Impulse Response ' Out1.name])
subplot(2,2,1)
impulse(Out1.dd)
title('Ydd')
subplot(2,2,2)
impulse(Out1.dq)
title('Yqd')
subplot(2,2,3)
impulse(Out1.dq)
title('Ydq')
subplot(2,2,4)
impulse(Out1.qq)
title('Yqq')
saveas(f2,['impulse' Out1.name '.emf'])
saveas(f2,['impulse' Out1.name '.jpeg'])
savefig(f2,['impulse' Out1.name])
%%
f3=figure
sgtitle(['Nyquist ' Out1.name])
subplot(2,2,1)
nyquist(Out1.dd)
title('Ydd')
subplot(2,2,2)
nyquist(Out1.dq)
title('Yqd')
subplot(2,2,3)
nyquist(Out1.dq)
title('Ydq')
subplot(2,2,4)
nyquist(Out1.qq)
title('Yqq')	
saveas(f3,['nyquist' Out1.name '.emf'])
saveas(f3,['nyquist' Out1.name '.jpeg'])
savefig(f3,['nyquist' Out1.name])
%%
f4=figure
sgtitle(['Nichols ' Out1.name])
subplot(2,2,1)
nichols(Out1.dd)
title('Ydd')
subplot(2,2,2)
nichols(Out1.dq)
title('Yqd')
subplot(2,2,3)
nichols(Out1.qd)
title('Ydq')
subplot(2,2,4)
nichols(Out1.qq)
title('Yqq')
saveas(f4,['Nichols' Out1.name '.emf'])
saveas(f4,['Nichols' Out1.name '.jpeg'])
savefig(f4,['Nichols' Out1.name])
%%
f5=figure
sgtitle(['Root Locus ' Out1.name])
subplot(2,2,1)
rlocus(Out1.dd)
title('Ydd')
subplot(2,2,2)
rlocus(Out1.dq)
title('Yqd')
subplot(2,2,3)
rlocus(Out1.qd)
title('Ydq')
subplot(2,2,4)
rlocus(Out1.qq)
title('Yqq')
saveas(f5,['rlocus' Out1.name '.emf'])
saveas(f5,['rlocus' Out1.name '.jpeg'])
savefig(f5,['rlocus' Out1.name])
end